### PR TITLE
Migrate frontend from Gatsby to NextJS 14

### PR DESCRIPTION
**Pull request by xinweny**
Experimentation of migration from Gatsby to [NextJS](https://nextjs.org/docs) for `bikespace_frontend` as discussed during the Civic Tech Hacknight on 16th July 2024. Static site generation is preserved through the `output: 'export'` option in `next.config.mjs`.

### Major changes
- `Makefile` now has a new command `make dev-frontend` that is required to run and watch the app in development mode. `make build-frontend` must now be run before `make run-frontend` (starts the production server).
- `/app` folder contains the router (See: [NextJS App Routing](https://nextjs.org/docs/app/building-your-application/routing))
- MD functionality from `gatsby-plugin-mdx` is now provided by `@next/mdx`. `page.mdx` content files are now co-located with regular `page.tsx` files in the App router
- Changes in `jest` configuration to work with NextJS setup
- Favicon is now required to display the logo outside the app (e.g. in tabs, Google search results, etc.) - `icon.ico` at root of `/app`
- Reduction in the number of dependencies, removing those related to Gatsby plugins, previous related bug fixes and config (e.g. `react-loader` to make dynamic import of `Plotly` compatible with Gatsby now replaced with NextJS's built-in solution `dynamic()`)
- Faster build times

### New additions
- [x] `umami` analytics added

Feel free to give the NextJS version in this branch a try and compare it with the Gatsby version in `develop`!

```
make dev-frontend
```

### CODE REVIEW

**Comment by sonalranjit** [comment]
Wow thanks for taking this on @xinweny , I think im okay with migrating to nextjs just purely on the reduction of dependencies. It really illustrates the bloat of gatsby, especially for the size of our application.

**Comment by xinweny** [comment]
Thanks for the feedback @sonalranjit! I also found that the dev experience is much smoother with NextJS - I managed to fix the custom date range bug because the error messages thrown by Next were a lot clearer, so I think maintaining the frontend code would be a lot easier moving forward. It was also a lot easier to integrate packages like `react-leaflet` and `plotly.js` to work with NextJS without needing extra dependencies.

**Comment by tallcoleman** [comment]
Just going to note the fix @xinweny shared with me in case anyone else has a similar issue with `make dev-frontend` command not working:

Add a file named `next-env.d.ts` with the following contents in the `bikespace_frontend` directory:
```
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
```

**Review by sonalranjit — APPROVED** [review]
Amazing, thanks @xinweny for this heavy lift

**Pull request merged**
