### PR TITLE
Add umami events to react app

### LINKED ISSUE #73: Adding analytics for the application
- [x] Landing page

  - completed in #97 

- [x] Dashboard

  - completed in #97 

- [x] Frontend

### PR DESCRIPTION
**Pull request by sonalranjit**
- added umami events to various react components for app.bikespace.ca

### CODE REVIEW

**Comment by hulloanson** [comment]
seems fine?

**Comment by sonalranjit** [comment]
> seems fine?

Yeah can I an approve @hulloanson

**Review by tallcoleman — APPROVED** [review]
Looks great, thanks for adding Sonal!

**Comment by tallcoleman** [comment]
@sonalranjit it looks like there's some JS minification that affects the events being registered in production, e.g. the Next button from the map pin page gets reported as `next-button-from-_` instead of `next-button-from-Location`

**Pull request merged**
