### PR TITLE
Epic: Merge bikespace_landing_page and bikespace_dashboard into bikespace_frontend

### LINKED ISSUE #133: Add dashboard layout into app
Part of the merging dashboard into react app effort

Move what we have here:

image

into the `bikespace_frontend` project

### PR DESCRIPTION
**Pull request by hulloanson**
# Reasons

- `bikespace_dashboard`'s state management was getting out of hand and was recreating a lot of what `react` and ecosystem has to offer
- `bikespace_landing_page` has a new design to implement
- easier styles and components reuse
- opens more possibilities to other user flows e.g. report issue in the "dashboard" map

# Goals

- [ ] Implement Bai's landing page design in `bikespace_frontend` (#142)
- [x] Re-implement `bikespace_dashboard` in `bikespace_frontend` (#134 and ongoing changes in `develop`)
- [ ] Configure deployment and gatsby settings so existing entrypoints (app.bikespace.ca, dashboard.bikespace.ca and bikespace.ca) are still usable

`develop` serves as the base of all these changes and when the time is right, we can merge (part of) the changes to `main` and deploy them.

### CODE REVIEW

**Comment by hulloanson** [comment]
Tagging @sonalranjit @tallcoleman @xinweny @AidanNPH for discussion

**Comment by tallcoleman** [comment]
@hulloanson @xinweny should I merge the [move-frontpage-to-app](https://github.com/bikespace/bikespace/tree/move-frontpage-to-app) branch into develop? Idea was to use some of gatsby's markdown plugins so that the page content could be written in markdown files.

**Comment by tallcoleman** [comment]
Also let me know if I should add in the API key for the Thunderforest base map that [dashboard.bikespace.ca](https://dashboard.bikespace.ca/) currently uses.

**Comment by hulloanson** [comment]
> @hulloanson @xinweny should I merge the [move-frontpage-to-app](https://github.com/bikespace/bikespace/tree/move-frontpage-to-app) branch into develop? Idea was to use some of gatsby's markdown plugins so that the page content could be written in markdown files.

We should! @xinweny has made quite some changes with `bikespace_frontend`

**Comment by hulloanson** [comment]
> Also let me know if I should add in the API key for the Thunderforest base map that [dashboard.bikespace.ca](https://dashboard.bikespace.ca/) currently uses.

Is the API key the one used here?

https://github.com/bikespace/bikespace/blob/develop/bikespace_frontend/src/components/dashboard/map/Map.tsx#L31

**Comment by xinweny** [comment]
> Also let me know if I should add in the API key for the Thunderforest base map that [dashboard.bikespace.ca](https://dashboard.bikespace.ca/) currently uses.

That would be great! I was wondering why the map styles looked different when I was integrating into React, I'm guessing this could likely be why.

**Comment by tallcoleman** [comment]
> > Also let me know if I should add in the API key for the Thunderforest base map that [dashboard.bikespace.ca](https://dashboard.bikespace.ca/) currently uses.
> 
> Is the API key the one used here?
> 
> https://github.com/bikespace/bikespace/blob/develop/bikespace_frontend/src/components/dashboard/map/Map.tsx#L31

Turns out it was in there already, the two tile layers were just overlapping. Committed a change so it picks just one.

**Comment by tallcoleman** [comment]
## Items to polish up before merging react dashboard into main

Mobile view tested via cloudflare preview link on iOS; desktop tested via Firefox on MacOS

### High Priority
- [x] On mobile - map credits z index is higher than menu drawer
- [x] On mobile - CSS is incorrectly calculating viewport height - causes drawer to appear to disappear when closed
- [x] Date filter selection and description field do not update with clear filter button
- [x] On mobile - Styling for panel nav, filter components, text in feed - should not be blue
- [x] On mobile - Opening drawer on feed view covers entire page instead of half
- [x] Date filter applied for last 7 appears to be incorrect - first date in described range is excluded?

### Med Priority
- [x] Styling for leaflet clusters - is currently set at default; previous dashboard had custom styling to align with brand colours
- [x] Problem type frequency graph should retain order when filter applied via click
- [x] Clear filter button does not reset styling on problem type frequency
- [x] Frequency by day graph should update style instead of zeroing out values when click to filter is applied
- [ ] URL specifiers for certain views or specific reports (previously implemented with hash(tag) router) not included – should at the very least include for specific reports
- [x] Styling logic for map pins and issue "chip" colours appears to be inconsistent and/or incorrect in both the map and the feed 

### Low Priority
- [x] Clear filters button may need additional vertical padding
- [x] Add a loading state for components so that they don't show "No Data" during load (not super noticeable if API response/internet is fast)

**Comment by tallcoleman** [comment]
Added one more issue to the fix list - "Styling logic for map pins and issue "chip" colours appears to be inconsistent and/or incorrect in both the map and the feed"

Examples:

Screenshot 2024-07-23 at 9 56 19 PM

Screenshot 2024-07-23 at 9 59 42 PM

Correct examples from existing dashboard:

Screenshot 2024-07-23 at 10 00 37 PM

Screenshot 2024-07-23 at 10 00 51 PM

**Comment by xinweny** [comment]
> Added one more issue to the fix list - "Styling logic for map pins and issue "chip" colours appears to be inconsistent and/or incorrect in both the map and the feed"
> 
> Examples:
> 
> Screenshot 2024-07-23 at 9 56 19 PM Screenshot 2024-07-23 at 9 59 42 PM
> Correct examples from existing dashboard:
> 
> Screenshot 2024-07-23 at 10 00 37 PM Screenshot 2024-07-23 at 10 00 51 PM

Fixed!

**Comment by xinweny** [comment]
I just introduced the following packages to handle the dashboard app state:
1. [Tanstack Query](https://tanstack.com/query/latest/docs/framework/react/overview) - tracks asynchronous state (fetching data from API to client, fetching all the submissions in our case)
2. [zustand](https://github.com/pmndrs/zustand) - tracks local state (e.g. submission filters, tabs, focused submission ID, etc.)

Tanstack Query makes it easier to introduce loading components like skeletons to specific components via the `isLoading` attribute from the return value of `useQuery()`.

Additionally, the code reads a bit cleaner without all the wrappers from using React Context with zustand.

**Comment by tallcoleman** [comment]
Added a fix for the iOS 100vh issue, but did notice one more problem -- clicking on an issue in the feed that is part of a map cluster does not open the cluster

Reference for fix to iOS 100vh issue: https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser

**Comment by xinweny** [comment]
> Added a fix for the iOS 100vh issue, but did notice one more problem -- clicking on an issue in the feed that is part of a map cluster does not open the cluster
> 
> Reference for fix to iOS 100vh issue: https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser

Thanks for the fix @tallcoleman!

I just pushed a fix to increase the zoom level so the map clusters now open up when the point is focused on.

**Comment by tallcoleman** [comment]
I think we might need to find another way to get the clusters to open; when I tried it, it opens the clusters, but it seems to be too zoomed in too far for leaflet to show the tiles properly.

Screenshot 2024-08-03 at 10 21 24 AM

> Thanks for the fix @tallcoleman!
> 
> I just pushed a fix to increase the zoom level so the map clusters now open up when the point is focused on.

**Comment by xinweny** [comment]
> I think we might need to find another way to get the clusters to open; when I tried it, it opens the clusters, but it seems to be too zoomed in too far for leaflet to show the tiles properly.
> 
> Screenshot 2024-08-03 at 10 21 24 AM
> > Thanks for the fix @tallcoleman!
> > I just pushed a fix to increase the zoom level so the map clusters now open up when the point is focused on.

Just pushed another fix, adjusted some parameters like `maxZoom` on the `<MapContainer />` component and added the `focusedId` to the `useEffect()` calling `map.invalidateSize()`, so this is called when the focused submission id changes. The tiles do load now, although quite slowly for me on Chrome - if anyone figures out a better fix that would be more than welcome.

**Comment by tallcoleman** [comment]
Spent some time working on this to-do this weekend:

> URL specifiers for certain views or specific reports (previously implemented with hash(tag) router) not included – should at the very least include for specific reports

The primary use case for this is to link to a specific issue, e.g. like this in the existing dashboard: https://dashboard.bikespace.ca/#feed?view_all=1&submission_id=1387 [1]. We used these links in the report of damaged bike parking locations we sent to the City in April.

I played around with implementing URL parameter navigation and had some success, but I think the proper way to implement it without making things buggy is to:

* Switch `useQuery` to `useSuspenseQuery` ([docs here](https://tanstack.com/query/latest/docs/framework/react/guides/suspense))
* Wrap query-dependent components in a [Suspense component](https://react.dev/reference/react/Suspense)
* Add loading fallbacks for those query-dependent components (e.g. replacing the current `queryResult.isPending` logic in `DashboardPage` and `ReportSummary`)
* `Map` components might still have some bugs to iron out because Leaflet has its own events system, but we'll see...

Thoughts?

[1]: Although the old dashboard uses the URL hash parameters for state navigation, it seems like support for regular parameters (e.g. `/dashboard?tab=filters` or `/dashboard?id=1387`) is better in next, so I went with regular parameters instead.

**Comment by tallcoleman** [comment]
Small improvement suggested by a user we could implement:

- [ ] Match issue type description to input instead of backend value

User feedback: "It's weird/confusing that when I selected the issue "parking not provided", on the confirmation page it said "none provided" as the issue. I'd expect the wording on the confirmation page to be similar to what I selected."

Example:
Screenshot 2024-08-17 at 11 57 26 AM
Screenshot 2024-08-17 at 11 57 47 AM

**Comment by sonalranjit** [comment]
@tallcoleman should we get this in? ~i can perform the DNS changes on the cloudflare once this is deployed to forward dashboard.bikespace to point to app.bikespace.ca/dashboard~ actually might not be to possible to do this on the DNS end. I think we'll have to update the landing page code and the frontend to use the new url for dashboard app.bikespace.ca/dashboard/

**Review by sonalranjit — APPROVED** [review]
LGTM

**Pull request merged**
